# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'ProlificLibrary' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 3.0’
  pod 'SwiftyJSON', '2.4.0'
  # Pods for ProlificLibrary

  target 'ProlificLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
